<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/functions.php';
$meta = page_meta(['title' => 'Sobre — ' . SITE_NAME, 'description' => 'Conheça a ideia e a pessoa por trás das Crônicas de um Cristão em Construção.', 'canonical' => url('sobre.php')]);
require __DIR__ . '/includes/header.php';
?>
<main id="conteudo">
    <header class="page-hero about-hero container"><span class="eyebrow">Sobre quem escreve</span><h1>Eu também estou<br><em>em construção.</em></h1><p>Esta é a parte em que eu deveria parecer pronto. Prefiro começar sendo honesto.</p></header>
    <section class="section about-story"><div class="container author-grid"><figure class="author-placeholder author-photo tall reveal"><picture><source srcset="assets/images/author-portrait.webp" type="image/webp"><img src="assets/images/author-portrait.png" width="1122" height="1402" loading="lazy" decoding="async" alt="Retrato do autor das Crônicas de um Cristão em Construção"></picture></figure><div class="story-copy reveal"><span class="eyebrow">Quem escreve · 01</span><h2>Uma apresentação<br><em>com humor</em></h2><p class="large-copy">Eu escrevo sobre uma coisa que conheço muito bem: <strong>a de estar em construção.</strong></p><p><mark><?= e(setting('author_name', 'Nome do autor a inserir')) ?></mark> — <?= e(setting('author_bio', 'Apresentação pessoal a inserir pelo autor.')) ?></p><p>No fim, talvez seja exatamente disso que estas crônicas tratem: de perceber que, entre aquilo que somos hoje e aquilo que Deus ainda está formando em nós, existe uma vida inteira acontecendo.</p></div></div></section>
    <section class="section paper-section"><div class="container prose-grid"><aside><span class="eyebrow">Por que existe · 02</span></aside><div><h2>Fé também cabe<br>na vida como ela é.</h2><p>O projeto nasceu da vontade de conversar sobre Deus de uma maneira humana, engraçada e prontas para dores complexas.</p><p>Aqui, espiritualidade não vive separada do resto. Ela aparece no trabalho, nas relações, na espera, na ansiedade, no humor e nos recomeços.</p></div></div></section>
    <section class="section values"><div class="container"><div class="section-heading"><div><span class="eyebrow">O que você encontra · 03</span><h2>Uma casa para<br><em>palavras honestas</em></h2></div></div><div class="topic-grid"><div class="topic"><span>01</span><h3>Humor</h3><p>Textos escritos de uma forma bem humorada.</p></div><div class="topic"><span>02</span><h3>Leveza</h3><p>Humor respeitoso para lembrar que somos humanos.</p></div><div class="topic"><span>03</span><h3>Esperança</h3><p>Sem negar a dor, mas sem deixar que ela seja a última palavra.</p></div><div class="topic"><span>04</span><h3>Caminho</h3><p>Fé como processo, encontro e transformação contínua.</p></div></div></div></section>
    <section class="manifesto section short-manifesto"><div class="container"><span class="eyebrow light">Um convite</span><h2>Se você também está aprendendo,<br><em>puxe uma cadeira.</em></h2><p>Não precisamos estar prontos para caminhar juntos.</p><a class="button button-light" href="cronicas.php">Começar uma leitura <span>→</span></a></div></section>
</main>
<?php require __DIR__ . '/includes/footer.php'; ?>
