<?php
$post = post_form_defaults($post ?? null);
$tagValue = is_array($post['tags'] ?? null) ? implode(', ', array_column($post['tags'], 'name')) : (string) ($post['tags'] ?? '');
?>
<?php if (!empty($errors)): ?><div class="admin-alert error" role="alert"><strong>Revise os campos:</strong><ul><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<form method="post" enctype="multipart/form-data" id="post-form"><?= csrf_field() ?>
<div class="admin-form-layout"><div class="admin-fields">
    <section class="admin-form-section"><h2>Conteúdo</h2><div class="admin-fields">
        <label class="admin-field">Título *<input type="text" name="title" value="<?= e($post['title']) ?>" maxlength="220" required data-title></label>
        <label class="admin-field">Slug *<input type="text" name="slug" value="<?= e($post['slug']) ?>" maxlength="240" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required data-slug><small>Gerado automaticamente, mas pode ser editado.</small></label>
        <label class="admin-field">Subtítulo<textarea name="subtitle" rows="2"><?= e($post['subtitle']) ?></textarea></label>
        <label class="admin-field">Resumo *<textarea name="excerpt" rows="4" maxlength="500" required><?= e($post['excerpt']) ?></textarea><small>Entre 10 e 500 caracteres.</small></label>
        <div class="admin-field"><span>Conteúdo HTML *</span><div class="editor-toolbar" aria-label="Ferramentas do editor"><button type="button" data-insert="<h2>|</h2>">Título</button><button type="button" data-insert="<strong>|</strong>"><strong>Negrito</strong></button><button type="button" data-insert="<em>|</em>"><em>Itálico</em></button><button type="button" data-insert="<blockquote><p>|</p></blockquote>">Citação</button><button type="button" data-insert="<ul><li>|</li></ul>">Lista</button><button type="button" data-insert="<a href=&quot;https://&quot;>|</a>">Link</button></div><textarea class="content-editor" name="content" required data-editor><?= e($post['content']) ?></textarea><small>HTML permitido e sanitizado no servidor. O tempo de leitura é calculado automaticamente.</small></div>
    </div></section>
    <section class="admin-form-section"><h2>SEO</h2><div class="admin-fields"><label class="admin-field">Meta title<input type="text" name="meta_title" maxlength="220" value="<?= e($post['meta_title']) ?>"></label><label class="admin-field">Meta description<textarea name="meta_description" maxlength="320" rows="3"><?= e($post['meta_description']) ?></textarea></label><label class="admin-field">Imagem Open Graph<input type="text" name="og_image" value="<?= e($post['og_image']) ?>" placeholder="https://... ou uploads/..."></label></div></section>
</div><aside class="admin-fields">
    <section class="admin-form-section"><h2>Publicação</h2><div class="admin-fields"><label class="admin-field">Status *<select name="status" required><?php foreach (['draft' => 'Rascunho', 'scheduled' => 'Agendado', 'published' => 'Publicado', 'archived' => 'Arquivado'] as $value => $label): ?><option value="<?= $value ?>" <?= $post['status'] === $value ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select></label><label class="admin-field">Data de publicação<input type="datetime-local" name="published_at" value="<?= e(datetime_input($post['published_at'])) ?>"></label><label class="check-field"><input type="checkbox" name="featured" value="1" <?= $post['featured'] ? 'checked' : '' ?>> Crônica em destaque</label></div></section>
    <section class="admin-form-section"><h2>Organização</h2><div class="admin-fields"><label class="admin-field">Categoria *<select name="category_id" required><option value="">Selecione</option><?php foreach ($categories as $category): ?><option value="<?= $category['id'] ?>" <?= (int) $post['category_id'] === (int) $category['id'] ? 'selected' : '' ?>><?= e($category['name']) ?></option><?php endforeach; ?></select></label><label class="admin-field">Tags<input type="text" name="tags" value="<?= e($tagValue) ?>" placeholder="oração, cotidiano, fé"><small>Separe por vírgulas.</small></label></div></section>
    <section class="admin-form-section"><h2>Imagem destacada</h2><label class="admin-field">JPG, PNG ou WebP<input type="file" name="featured_image" accept="image/jpeg,image/png,image/webp"><small>Máximo 5 MB.</small></label><?php if ($post['featured_image']): ?><p class="help-box">Imagem atual: <?= e($post['featured_image']) ?></p><?php endif; ?></section>
</aside></div>
<div class="admin-actions"><button class="admin-button primary" type="submit">Salvar crônica</button><?php if ($post['id']): ?><a class="admin-button" href="<?= e(admin_url('posts/preview.php?id=' . $post['id'])) ?>" target="_blank">Visualizar ↗</a><?php endif; ?><a class="admin-button" href="<?= e(admin_url('posts/index.php')) ?>">Cancelar</a></div></form>
